<?php
/**
 * @author 韩威兵^life <1877361302@qq.com>
 * @copyright 2016 - 2016 粮易网 <jztl2012@163.com>
 * @version $Id: 2016/8/25 18:11 ly2.0 GroupController.class.php 韩威兵^life $
 */
namespace Admin\Controller\Member;
use Think\Controller;
use Think\Auth;
use Admin\Controller\Home\IndexController;

class GroupController extends IndexController {
	public function _initialize() {
		parent::_initialize(); // TODO: Change the autogenerated stub
	}


	/**
	 *权限组列表
	 */
	public function index() {
		$model_atth = M('auth_group');
		$list       = $model_atth->select();
		$this->assign('list', $list);
		$this->display();
	}


	/**
	 *增加权限组
	 */
	public function add() {
		header("Content-type: text/html; charset=utf-8");
		$model_menu = M('admin_menu');
		$model_auth = M('auth_group');
		$title      = I('title');

		if ($title) {
			$data   = $this->do_add($model_auth);
			$add_id = $model_auth->data($data)->add();
			if ($add_id) {
				$this->success('添加成功！', U('index'));
			} else {
				$this->error('添加失败！');
			}
		} else {
			$this->show_add($model_menu);

			$this->display();
		}
	}


	/**
	 * 增加之前整理数据
	 */
	public function do_add($model_auth) {
		$data['title']  = I('title');
		$data['status'] = I('status');
		$top_list       = I('top_list');
		$second_list    = I('second_list');
		$three_list     = I('three_list');
		$data['top']    = implode(',', $top_list);
		$data['second'] = implode(',', $second_list);
		$data['three']  = implode(',', $three_list);

		return $data;
	}


	/**
	 * 增加显示层回调函数
	 */
	public function show_add($model_menu, $top = '', $second = '', $three = '') {
		$where['rank'] = 1;
		$top_list      = $model_menu->where($where)->select();
		foreach ($top_list as $k => $v) {
			//判断顶级菜单
			if ($top) {
				if (in_array($v['top'], $top)) {
					$top_list[$k]['checked'] = 'checked="true"';
				}
			}
			$where['rank']          = 2;
			$where['top']           = $v['top'];
			$where['second']        = array('neq', '');
			$top_list[$k]['second'] = $model_menu->where($where)->select();
			foreach ($top_list[$k]['second'] as $kk => $vv) {
				if ($second) {
					$old_second = $vv['top'] . '/' . $vv['second'];
					if (in_array($old_second, $second)) {
						$top_list[$k]['second'][$kk]['checked'] = 'checked="true"';
					}
				}
				$where['rank']                        = 3;
				$where['top']                         = $v['top'];
				$where['second']                      = $vv['second'];
				$top_list[$k]['second'][$kk]['three'] = $model_menu->where($where)->select();
				foreach ($top_list[$k]['second'][$kk]['three'] as $kkk => $vvv) {
					if ($three) {
						$old_three = $vvv['top'] . '/' . $vvv['second'] . '/' . $vvv['three'];
						if (in_array($old_three, $three)) {
							$top_list[$k]['second'][$kk]['three'][$kkk]['checked'] = 'checked="true"';
						}
					}
				}
			}


			$this->assign('top_list', $top_list);
		}
	}


	/**
	 * 修改权限组
	 */
	public function edit() {
		$id = post('id', 'intval', 0);

		$model_auth = M('auth_group');
		$model_menu = M('admin_menu');
		//判断是显示层回调还是修改方法
		if ($id) {
			//修改方法

			$data = $this->do_add($model_auth);
			$res  = $model_auth->where('id=' . $id)->data($data)->save();
			if ($res) {
				$this->success('修改成功！', U('index'));
			} else {
				$this->error('修改失败！');
			}
		} else {
			$id    = I('id');
			$field = $model_auth->where('id=' . $id)->find();
			if ($field['top']) {
				$top = explode(',', $field['top']);
			}
			if ($field['second']) {
				$second = explode(',', $field['second']);
			}
			if ($field['three']) {
				$three = explode(',', $field['three']);
			}

			$this->assign('field', $field);
			$this->show_add($model_menu, $top, $second, $three);
			$this->display('add');
		}
	}


	/**
	 * 删除
	 */
	public function delete() {
		$this->paner_delete(M('auth_group'));
	}
}
